# GENERATED by scripts/formula.sh — do not hand-edit. Regenerate with:
#   scripts/formula.sh <release-tag> > Formula/wigolo.rb
class Wigolo < Formula
  desc "Local-first web intelligence for AI agents"
  homepage "https://github.com/KnockOutEZ/wigolo"
  version "0.2.1"
  license "AGPL-3.0-only"

  # One prebuilt archive per platform, straight off the release page — the artifact IS the
  # build, so there is no source path, no bottle and nothing to compile here.
  on_macos do
    on_arm do
      url "https://github.com/KnockOutEZ/wigolo/releases/download/binary-v0.2.1-sd507.1/wigolo-0.2.1-darwin-arm64.tar.gz"
      sha256 "611e7049fd09ca13ae006e2d25450bb25d4c34e3a5f94bc2f3091c884070b2b8"
    end
    on_intel do
      url "https://github.com/KnockOutEZ/wigolo/releases/download/binary-v0.2.1-sd507.1/wigolo-0.2.1-darwin-x64.tar.gz"
      sha256 "cfcaafaaf773b41f7ee83a7b79c5ea6c4eabb6aa85fb234a497ec966949cc615"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/KnockOutEZ/wigolo/releases/download/binary-v0.2.1-sd507.1/wigolo-0.2.1-linux-arm64.tar.gz"
      sha256 "ac30555e20db35da91cc446b31a85fa9256024f82e8ecc751b6c802676b0663f"
    end
    on_intel do
      url "https://github.com/KnockOutEZ/wigolo/releases/download/binary-v0.2.1-sd507.1/wigolo-0.2.1-linux-x64.tar.gz"
      sha256 "16db0c8e7621f1333b8bdcea25ccaf2227d05ee6f47863408a25079f6cc703ef"
    end
  end

  livecheck do
    url :homepage
    regex(%r{href=.*?/tag/v?(\d+(?:\.\d+)+)["' >]}i)
  end

  # The archive already has the layout the executable expects — `bin/wigolo` resolves
  # `libexec/` relative to its own realpath — so installing is moving that tree into the keg
  # intact. Brew links `<keg>/bin/wigolo` into the prefix as a symlink; realpath resolution is
  # what makes that safe.
  def install
    prefix.install "bin", "libexec", "LICENSES", "VERSION"
  end

  # The cleaner strips executables and prunes what looks like build residue. Both are wrong
  # here: stripping a self-contained executable breaks the embedded payload and invalidates the
  # macOS signature, and `libexec/` is a payload whose layout belongs to the build pipeline.
  skip_clean "bin", "libexec"

  test do
    assert_match version.to_s, shell_output("#{bin}/wigolo --version")
    # G5, asserted the way a consumer can: `VERSION` is `key=value` lines, and `semver=` in
    # it has to be the version this formula claims to have installed.
    assert_equal "semver=#{version}", (prefix/"VERSION").read.lines.grep(/^semver=/).first.strip
  end
end
