#!/bin/sh
# Emit `Formula/wigolo.rb` for one published wigolo binary release, on stdout.
#
# The formula is GENERATED, never hand-edited: every field that differs between releases is a
# url, a sha256 or the version, and all of them come from the release's own `SHA256SUMS`. A
# targeted sed over a checked-in .rb would have to find four url/sha256 pairs by position in a
# Ruby file; regenerating the whole file from the one authoritative input cannot half-apply.
#
# usage: scripts/formula.sh <tag>
#
# Reads the release's `SHA256SUMS` over HTTPS. No token: the wigolo repo is public, and this
# script must produce the same bytes for a maintainer running it by hand as for the bump
# workflow running it in CI.
set -eu

REPO="${WIGOLO_REPO:-KnockOutEZ/wigolo}"
BASE="${WIGOLO_RELEASE_BASE:-https://github.com/$REPO/releases/download}"

TAG="${1:-}"
[ -n "$TAG" ] || { echo "usage: scripts/formula.sh <tag>" >&2; exit 2; }

SUMS="$(curl -fsSL "$BASE/$TAG/SHA256SUMS")" || {
  echo "no SHA256SUMS asset on release $TAG of $REPO" >&2; exit 1
}

# `$2 == name`, not a regex: SHA256SUMS is `<hex>  <name>` with two spaces, and a substring
# match would let `wigolo-1.0.0-darwin-arm64.tar.gz` answer for `...-arm64.tar.gz`.
sum_of() {
  printf '%s\n' "$SUMS" | awk -v name="$1" '$2 == name { print $1; exit }'
}

# The version is read out of an asset NAME rather than passed in, so the formula can never
# claim a version the assets it points at do not carry.
VERSION="$(printf '%s\n' "$SUMS" \
  | awk '$2 ~ /^wigolo-.*-darwin-arm64\.tar\.gz$/ { n = $2; sub(/^wigolo-/, "", n); sub(/-darwin-arm64\.tar\.gz$/, "", n); print n; exit }')"
[ -n "$VERSION" ] || { echo "release $TAG has no darwin-arm64 asset to read a version from" >&2; exit 1; }

emit_platform() {
  name="wigolo-$VERSION-$1.tar.gz"
  sha="$(sum_of "$name")"
  [ -n "$sha" ] || { echo "release $TAG has no checksum for $name" >&2; exit 1; }
  printf '      url "%s/%s/%s"\n' "$BASE" "$TAG" "$name"
  printf '      sha256 "%s"\n' "$sha"
}

cat <<RB
# GENERATED by scripts/formula.sh — do not hand-edit. Regenerate with:
#   scripts/formula.sh <release-tag> > Formula/wigolo.rb
class Wigolo < Formula
  desc "Local-first web intelligence for AI agents"
  homepage "https://github.com/$REPO"
  version "$VERSION"
  license "AGPL-3.0-only"

  livecheck do
    url :homepage
    regex(%r{href=.*?/tag/v?(\d+(?:\.\d+)+)["' >]}i)
  end

  # One prebuilt archive per platform, straight off the release page — the artifact IS the
  # build, so there is no source path, no bottle and nothing to compile here.
  on_macos do
    on_arm do
$(emit_platform darwin-arm64)
    end
    on_intel do
$(emit_platform darwin-x64)
    end
  end

  on_linux do
    on_arm do
$(emit_platform linux-arm64)
    end
    on_intel do
$(emit_platform linux-x64)
    end
  end

  # The cleaner strips executables and prunes what looks like build residue. Both are wrong
  # here: stripping a self-contained executable breaks the embedded payload and invalidates the
  # macOS signature, and \`libexec/\` is a payload whose layout belongs to the build pipeline.
  skip_clean "bin", "libexec"

  # The archive already has the layout the executable expects — \`bin/wigolo\` resolves
  # \`libexec/\` relative to its own realpath — so installing is moving that tree into the keg
  # intact. Brew links \`<keg>/bin/wigolo\` into the prefix as a symlink; realpath resolution is
  # what makes that safe.
  def install
    prefix.install "bin", "libexec", "LICENSES", "VERSION"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/wigolo --version")
    # G5, asserted the way a consumer can: \`VERSION\` is \`key=value\` lines, and \`semver=\` in
    # it has to be the version this formula claims to have installed.
    assert_equal "semver=#{version}", (prefix/"VERSION").read.lines.grep(/^semver=/).first.strip
  end
end
RB
